// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC46KxoSUqJcvUoHNTbPs_VvJdI1xPbDJU',
    appId: '1:1096670003780:web:ecab4e3eefac5047b4b211',
    messagingSenderId: '1096670003780',
    projectId: 'terapia-mais-definitivo',
    authDomain: 'terapia-mais-definitivo.firebaseapp.com',
    storageBucket: 'terapia-mais-definitivo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFs6A5K3v3oRuoweIcu6zEHV2wvVUVUB0',
    appId: '1:1096670003780:android:1921170c9d61b9cab4b211',
    messagingSenderId: '1096670003780',
    projectId: 'terapia-mais-definitivo',
    storageBucket: 'terapia-mais-definitivo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM6lKRgvPxyP_1caK7pN9AT0nK9cUNH2E',
    appId: '1:1096670003780:ios:afeb387e0b3a0580b4b211',
    messagingSenderId: '1096670003780',
    projectId: 'terapia-mais-definitivo',
    storageBucket: 'terapia-mais-definitivo.firebasestorage.app',
    iosBundleId: 'com.example.terapiaMais4terapeutas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM6lKRgvPxyP_1caK7pN9AT0nK9cUNH2E',
    appId: '1:1096670003780:ios:afeb387e0b3a0580b4b211',
    messagingSenderId: '1096670003780',
    projectId: 'terapia-mais-definitivo',
    storageBucket: 'terapia-mais-definitivo.firebasestorage.app',
    iosBundleId: 'com.example.terapiaMais4terapeutas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC46KxoSUqJcvUoHNTbPs_VvJdI1xPbDJU',
    appId: '1:1096670003780:web:e2982742e1f0e918b4b211',
    messagingSenderId: '1096670003780',
    projectId: 'terapia-mais-definitivo',
    authDomain: 'terapia-mais-definitivo.firebaseapp.com',
    storageBucket: 'terapia-mais-definitivo.firebasestorage.app',
  );

}