// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTq8LbHzYYXqeKR1daIRqTNhnE_Rs5qzs',
    appId: '1:342160446341:web:628720361ea025a6ab2aec',
    messagingSenderId: '342160446341',
    projectId: 'terapia-mais',
    authDomain: 'terapia-mais.firebaseapp.com',
    storageBucket: 'terapia-mais.firebasestorage.app',
    measurementId: 'G-FCZDVE208P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqe6jzrSAmNCiK3CJzf1Y8AWljYEZvdQ',
    appId: '1:342160446341:android:8348ef381e34fbdaab2aec',
    messagingSenderId: '342160446341',
    projectId: 'terapia-mais',
    storageBucket: 'terapia-mais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMrtGXYwxLqpHgfVvezjXfGMNimPXoFTs',
    appId: '1:342160446341:ios:b34ad31a97a84a65ab2aec',
    messagingSenderId: '342160446341',
    projectId: 'terapia-mais',
    storageBucket: 'terapia-mais.firebasestorage.app',
    iosClientId: '342160446341-jhgnubfj6lukjsrsjlaff7u5uiv02ass.apps.googleusercontent.com',
    iosBundleId: 'com.example.terapiaMais4terapeutas',
  );
}
